### ISSUE TITLE
Cannot use tool on windows machine due baseCommand 'ng g' cannot run

### ISSUE THREAD

**Issue by Artur51** [cyrilletuzi/vscode-angular-schematics#685]
Hi, 
I have installed this extension and it does not work on my windows pc. All the command-line shells I have on this pc do not support "ng" execution but supports "npx ng" instead. Could you please introduce a fix for this case? 

Thank you!

**Comment by cyrilletuzi** [comment]
Hi,

As mentioned in the [extension documentation](https://github.com/cyrilletuzi/vscode-angular-schematics/blob/main/docs/TROUBLESHOOTING.md), it is currently required to have Angular CLI installed. The [official Angular documentation](https://angular.io/guide/setup-local#install-the-angular-cli) does to. So this is not an issue, it is working as intended.

Adding support for another base command is already discussed in #430 and #610. But it is not so simple to add. If there is a specific reason why you can't simply do a `npm install @angular/cli -g`, please mention it in one of the discussions.

**Comment by Artur51** [comment]
Hello.
I have it installed. I cannot run it but only using npx as the base prefix
command.


пн, 6 сент. 2021 г., 10:34 Cyrille Tuzi ***@***.***>:

**Comment by Artur51** [comment]
Please implement settings checkbox for this, if possible. I believe my
machine is not the only one with the same behavior due the solutions to run
ng i have googled

пн, 6 сент. 2021 г., 10:53 Artur Zuravljov ***@***.***>:

**Comment by cyrilletuzi** [comment]
If `@angular/cli` is installed globally, direct `ng g` commands should work, and it is not related to this extension.

The most frequent cause of this problem is that `npm install @angular/cli -g` has been done in a shell different from the one used in VS Code (for example, doing the global install in cmd, then using PowerShell in VS Code). Doing `npm install @angular/cli -g` directly in VS Code terminal (instead of an external terminal), and then restarting VS Code, should solve the issue. The [troubleshooting guide](https://github.com/cyrilletuzi/vscode-angular-schematics/blob/main/docs/TROUBLESHOOTING.md) already explains this.

**Comment by Artur51** [comment]
I tryed before and Just have tryed install globally once again with the
command you sent. Still not work for ne when i run ng after installation.

пн, 6 сент. 2021 г., 10:34 Cyrille Tuzi ***@***.***>:

**Comment by Artur51** [comment]
Just have done fron VS code terminal and restarted... Ng Not working after
restartin terminal. Something else maybe need to be done.

пн, 6 сент. 2021 г., 10:34 Cyrille Tuzi ***@***.***>:

**Comment by Artur51** [comment]
If the enu setting is difficult to implement then maybe you can get some
environment property. User can provide instead of default base command?

пн, 6 сент. 2021 г., 10:34 Cyrille Tuzi ***@***.***>:
